### ISSUE TITLE
Faltó descripción y foto

### ISSUE THREAD

**Issue by asanzo** [pdepjm/2021-kata0-prensentacion-reginaloustau#1]
¡Hola @reginaloustau !

Te faltó la descripción y la foto, fijate que leyendo la kata 0 te lo pide. 

Cualquier cosa nos avisás!!

Saludos!

**Comment by reginaloustau** [comment]
Ya lo agregue

**Comment by reginaloustau** [comment]
No se si lo tenia que cerrar

**Comment by asanzo** [comment]
Cuando el issue está resuelto, está perfecto cerrarlo :+1:
